version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 090605004529.dkr.ecr.eu-central-1.amazonaws.com
      - REPOSITORY_NAME=ai-recruiter-backend
      - IMAGE_TAG=${CODEBUILD_BUILD_NUMBER}
      - IMAGE_URI=090605004529.dkr.ecr.eu-central-1.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG
      - LATEST_URI=090605004529.dkr.ecr.eu-central-1.amazonaws.com/$REPOSITORY_NAME:latest
      
  build:
    commands:
      - echo Build started at $(date)
      - echo Building the Docker image...
      - docker build -t ${IMAGE_URI} backend/
      - docker tag ${IMAGE_URI} ${LATEST_URI}
      
  post_build:
    commands:
      - echo Build completed at $(date)
      - echo Pushing the Docker images...
      - docker push ${IMAGE_URI}
      - docker push ${LATEST_URI}
      - printf '[{"name":"ai-recruiter-backend","imageUri":"%s"}]' ${LATEST_URI} > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - '/root/.docker/**/*'
